/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

export type U128Input = { upper: BigNumberish; lower: BigNumberish };

export type U128Output = { upper: BN; lower: BN };

interface BilliardAbiInterface extends Interface {
  functions: {
    init: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "init",
    values: [BigNumberish, BigNumberish]
  ): Uint8Array;

  decodeFunctionData(functionFragment: "init", data: BytesLike): DecodedValue;
}

export class BilliardAbi extends Contract {
  interface: BilliardAbiInterface;
  functions: {
    init: InvokeFunction<
      [start_x: BigNumberish, start_y: BigNumberish],
      [U128Output, U128Output]
    >;
  };
}
