/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BilliardAbi } from "./BilliardAbi";

export { BilliardAbi__factory } from "./factories/BilliardAbi__factory";
